### ISSUE TITLE
[Feature Request] Consider Incorporating Simple Actuarial Table for End Date

### ISSUE THREAD

**Issue by alraban** [gvol/emacs-memento-mori#1]
The reminder of mortality might be a little more pointed with a likely "end" date.  That information could be easily gotten from general purpose actuarial tables available from public sources, see e.g.: https://www.ssa.gov/oact/STATS/table4c6.html

As you can see from the chart there's a "further" life expectancy provided for any given age.  I'd personally find it more motivating to see the time I (likely) have left (life expectancy) rather than the time I've already spent (age) in the mode line.  It could be expressed as age/likely-age-of-death, or age/years-left, or there could just be a toggle for which of the two you want to see.  

Thanks for considering.  In any case, this is already a really neat package, thanks for writing it!

**Comment by lassik** [comment]
Glad to hear you like it! I wasn't sure if anybody else would :)

I know it sounds like common sense to expect that showing the _time left_ instead of _time elapsed_ would carry more weight. However, before writing this package I actually ran the [Death Clock extension for Chrome](https://chrome.google.com/webstore/detail/death-clock/nddjbfjdamhcmdcghehomomgppbigjam) for several months. It shows the number of days left every time you open a new browser tab, and it didn't speak to me much. Part of it may be that it shows the number of days left (which for most people is many thousands) instead of years, so it's difficult to pay attention when a few days have passed.

For this package, I picked the age as people usually talk about it, because people are used to thinking about their age all their lives in lots of different contexts. So we are raised from an early age to think that number is really important and we already have a good feel for what different age numbers mean for human life. The situation is similar to calendar systems - there's no absolute reason to prefer a particular starting year or week length for a calendar, but social conventions make it easier to think about some representations than others.

Another reason to prefer the age is that it's unambiguous. Life expectancy is impossible to predict - you just have to pick a number, and anyone can pick their own criteria which may or may not turn out to be true.

However, if you try the age thing for a while and it doesn't impress you even with these arguments, I'm open to adding an option to set the predicted death date instead of birth date. It's not a big effort to offer alternatives.

**Comment by lassik** [comment]
Another point about showing time remaining is, when I did that with the Chrome extension, I noticed that I don't take it seriously. Whenever I didn't feel like facing up to something, I could weasel out of it by thinking that I picked the date arbitrarily. Your age is absolute; you can't weasel out of it and think that it's not your actual age.

**Comment by lassik** [comment]
Yet another reason to prefer the age is that though someone may have many decades left, their physical and mental fitness starts to decrease much earlier. For many people there is unfortunately a rapid and unexpected decrease at the onset of an illness (whether it's age- or lifestyle-related or not). Other kinds of major setbacks can happen too, e.g. financial or reputational. So the earlier one starts to work on an important life goal, the better. It's not wise to live from the mindset that one has 40 years left if one is unlikely to be able to pursue many important life goals during the last 30 of them. In that case it's wiser to assume that one has only 10 years left to pursue the goals, and any extra years beyond that are a bonus.

**Comment by lassik** [comment]
For a "years left" counter, it might make more sense to show "years left before you are likely to develop health issues so you cannot continue the lifestyle you are used to, based on your health habits". That might actually be really great!

**Comment by lassik** [comment]
For a "years left" counter, it might make more sense to show "years left before you are likely to develop health issues so you cannot continue the lifestyle you are used to, based on your health habits".

**Comment by alraban** [comment]
I can certainly see your points; I think I may have slightly miscommunicated my suggestion though.  What I'd ideally like to see is both current age and "years left" shown next to one another, which is a bit like a progress bar or an hourglass ticking away as you see hundredths of years moving from one side to the other, week by week, if you take my point.  Something like XX.XX/YY.YY where XX.XX is age and YY.YY is likely years left.  I certainly agree that using days (ala Death Clock) is a silly way to represent the data as we don't usually measure long periods of time in days, so 3650 days doesn't mean much intuitively, but 10 years is much easier to "grok."  

To offer a counterpoint in favor of joint presentation, while one's age is more familiar and meaningful, it's also known and immediate.  I know my age without thinking about it at all.  I _don't_ have a good intuitive grip for how many years I might reasonably expect to live on average, or how that number compares to how many I've already lived.  If I were, for example, at the half way point (actuarially speaking), I think seeing something like 41.05/41.05 (denoting ~41 years lived and ~41 remaining on average) would be a much more powerful commentary on my mortality than just seeing that I'm 41.05.  What's especially interesting about actuarial tables is that one's "end date" keeps moving farther out as you live longer and don't die--that is to say your actuarial years left decrease over time, but at a slower rate than the rate at which you are aging, which, given the way averages work, is a necessary consequence but is neat to see played out in numbers in real time.  If you'll pardon an aside, it's like a mathematical embodiment of the Stoic idea that no one is so old that they can't in good conscience hope for at least one more day (although of course no one is guaranteed any further time).  

As to arbitrariness, any end date for an indiviudal will of course be somewhat arbitrary because we can't see the future, but we don't have to just pick a number:  statistics can tell us what the average end date for any person will be which is a starting point.  I suggested using actuarial life tables because they are easy for a user (only two variables), are publicly available, and are data-driven (i.e. they're very likely to be true on average because they're developed with actual mortality data).  While I find the idea of "healthy years" remaining to be interesting, I think likely "healthy years" is a much harder and more fact-specific question: there are readily identifiable characteristics that forecast reduced mobility later in life, and likewise with reduced mental function, but those factors are not all the same, etc. I also don't know where to find data-driven publicly available tables on that, although there are a few multi-variable life calculators out there that you might be able to find the data behind if you poked around.  That means that attempts to show "healthy years" accurately will be challenging, and if you just pick a number (like leaving off the last 10 or 20 or...) that would be an even more arbitrary result than just using the life tables.  Some people are sharp and mobile into their 90's, others are not.  That said, if you've got good data on tap for it and can identify good inputs, "healthy years" would be very exciting to see implemented!

In any case, I appreciate the thoughtful consideration you've already given the issue!  I completely understand where you're coming from on preferring to just have age listed, even if I don't entirely agree.  Thanks sincerely for an interesting discussion regardless of how you land on the feature request :-)

**Comment by lassik** [comment]
> If I were, for example, at the half way point (actuarially speaking), I think seeing something like 41.05/41.05 (denoting ~41 years lived and ~41 remaining on average) would be a much more powerful commentary on my mortality than just seeing that I'm 41.05.

OK, so you'd like to show _both_ time elapsed and time remaining. That's interesting - I hadn't thought of that possibility.

> What's especially interesting about actuarial tables is that one's "end date" keeps moving farther out as you live longer and don't die--that is to say your actuarial years left decrease over time, but at a slower rate than the rate at which you are aging, which, given the way averages work, is a necessary consequence but is neat to see played out in numbers in real time.

That's fun :) I'd never thought or heard about that but it makes sense. Thanks for bringing this to our attention. I'd imagine most users of a _memento mori_ app appreciate insights like this.

> I suggested using actuarial life tables because they are **easy** for a user (only two variables), are publicly available, and are data-driven (i.e. they're very likely to be true on average because they're developed with actual mortality data). While I find the idea of "healthy years" remaining to be interesting, I think likely "healthy years" is a **much harder** and more fact-specific question:

You are correct, but frankly I think people who go for the easy answer are deluding themselves. I bolded the words **easy** and **harder** to emphasize my point. There are people in every field who offer an easy answer to the wrong question, because the right questions don't have easy answers. Often those people are very popular, but I have no desire to join them. Speaking from personal experience, I watched two of my grandparents lose the ability to communicate effectively. That gives pause. So when planning your life conservatively, the first measure is to take it as axiomatic that you won't live over eighty. (You may live, but it's best to assume at a very reduced capacity.)

Then again, medical technology is getting better fast. Just yesterday [Neuralink explained their plans for a high-bandwidth brain interface](https://www.youtube.com/watch?v=r-vbh3t7WVI) in a fascinating presentation. So for those of us who are fortunate enough to have 2-3 or more decades of life expectancy, it's difficult to predict what will happen. In that case actuarial tables are also not useful because things change too fast for statistics to catch up.

In any case, for this humble package, we can make it so you can:

* input either your birth date, or an arbitrary end date, or both at once
* and choose to show either years elapsed, years left, or both at once

Then people can use their own criteria to pick an end date. This would be the easiest way to solve everyone's use cases.

**Comment by lassik** [comment]
Sorry, I didn't explain myself properly either.

> That means that attempts to show "healthy years" accurately will be challenging, and if you just pick a number (like leaving off the last 10 or 20 or...) that would be an even more arbitrary result than just using the life tables. Some people are sharp and mobile into their 90's, others are not.

The point is to pick a conservative estimate: err on the side of caution. There's no harm in getting to major life goals sooner (unless you're a Silicon Valley / Wall Street extreme overachiever type). But if you live by an optimistic estimate and reality turns out significantly worse, you lose those goals forever.

**Comment by alraban** [comment]
Letting users pick an end date for optional display would certainly work for my use case.  Thanks for the food for thought as well!

**Comment by gvol** [comment]
I created https://gitlab.com/gvol/memento.el which allows customization of dates (and allows multiple messages choosing one at random).  I probably should have tried to incorporate it into this package first since the world probably doesn't need two Emacs memento-mori packages.  :)  
@lassik, would you like me to try to do that?  Otherwise, I'm hoping to put it up on MELPA or maybe GNU ELPA.

**Comment by gvol** [comment]
@alraban, my plans for now are to just let the user input an end date (which is available as of a little while ago).  I do like the idea of including an actuarial table so that the end date keeps moving, but as I started to look into it, I kept wanting to make it more and more accurate which I feel like would have been overkill for this package.

If you would still like to have an actuarial table included feel free to submit a pull request, or reopen this issue, but based on a prior comment of yours I'm going to close it as satisfied for now.
